version: '3.3'
services:
  web:
    image: atlassian/confluence-server:8.5.3
    ports:
      - "8090:8090"
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - db
    environment:
      - CATALINA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5008
  db:
    image: postgres:12.8-alpine
    ports:
      - "4444:4321"
    environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=confluence